username = input("Введите ваше имя: ")
title = input("Введите заголовок заметки: ")
content = input("Введите описание заметки: ")
status = input("Введите статус заметки: ")
created_date = input("Дата создания заметки ДД-ММ-ГГГГ: ")
issue_date = input("Срок исполнения ДД-ММ-ГГГГ: ")
